-- ============================================================
-- TirePro Default Seed Data
-- Microsoft SQL Server (T-SQL)
--
-- Run AFTER schema.sql.
-- Seeds the default organization, branch, settings, tire types,
-- and service products.  Safe to re-run — all inserts are guarded
-- by existence checks.
--
-- For demo customers/suppliers/tires/sales run:
--   node server/seed.js
-- ============================================================

USE TireProDB;
GO

-- ── Default organization ─────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM organizations WHERE code = 'TIREPRO')
INSERT INTO organizations (name, code, type, currency)
VALUES ('TirePro', 'TIREPRO', 'retail', 'PKR');
GO

-- ── Default branch ───────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM branches WHERE organization_id = 1 AND code = 'MAIN')
INSERT INTO branches (organization_id, name, code)
VALUES (1, 'Main Branch', 'MAIN');
GO

-- ── Default settings ─────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM settings WHERE organization_id = 1)
BEGIN
    INSERT INTO settings (organization_id, [key], value) VALUES
        (1, 'company_name',        'TirePro'),
        (1, 'company_tagline',     'Tyre & Wheel Solutions'),
        (1, 'company_address',     '123 Industrial Zone, Lahore, Pakistan'),
        (1, 'company_phone',       '+92-42-1234567'),
        (1, 'company_email',       'info@tirepro.pk'),
        (1, 'invoice_prefix',      'INV'),
        (1, 'po_prefix',           'PO'),
        (1, 'default_tax_rate',    '15'),
        (1, 'payment_due_days',    '30'),
        (1, 'default_sale_status', 'pending'),
        (1, 'currency',            'PKR'),
        (1, 'announcement',        ''),
        (1, 'refresh_interval',    '60');
END
GO

-- ── Tire types ───────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM tire_types)
INSERT INTO tire_types (name, sort_order) VALUES
    ('Passenger',    0),
    ('SUV',          1),
    ('4x4',          2),
    ('LT',           3),
    ('Performance',  4),
    ('Motorcycle',   5);
GO

-- ── Default services ─────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM products WHERE organization_id = 1 AND category = 'Service')
INSERT INTO products (organization_id, name, description, category, unit, sale_price, cost_price, is_active) VALUES
    (1, 'Tire Fitting',      'Mount and fit tyre to wheel rim',            'Service', 'job', 300,  100, 1),
    (1, 'Wheel Balancing',   'Dynamic wheel balancing with weights',        'Service', 'job', 250,  80,  1),
    (1, 'Wheel Alignment',   '4-wheel laser alignment',                     'Service', 'job', 1500, 500, 1),
    (1, 'Puncture Repair',   'Tubeless puncture plug and patch repair',     'Service', 'job', 200,  50,  1),
    (1, 'Valve Replacement', 'Replace tyre valve stem',                     'Service', 'job', 100,  30,  1);
GO

-- ── Admin user ───────────────────────────────────────────────────────────────
-- NOTE: Password hash is generated by the server on first start using ADMIN_PASSWORD from .env
-- Do NOT insert a plaintext password here — let the Node.js app seed the admin account.
-- The server/db.js setupDatabase() function handles this securely with bcrypt.
PRINT 'Seed data applied. Start the server to auto-seed the admin user account.';
GO
